const products = [
  {
    id: "1",
    name: "Fresh Apple ",
    description:
      "Fresh Apple with a refreshing taste that helps nourish the body, It contains required body nutrients ranging from vitamins to minerals",
    img: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2070&q=80",
    price: "30",
    discount: "14.67",
    freshness: "Fresh",
    farm: "Farm Pride",
    avgRating: "4",
    stock: "200",
    deliveredTo: "Ilorin",
    estimatedDeliveryDays: "1",
    deliveryMode: "free",
    category: "fruits and vegetables",
  },
  {
    id: "2",
    name: "Fresh Bread ",
    description:
      "Fresh Bread  with a refreshing taste that helps nourish the body, It contains required body nutrients ranging from vitamins to minerals",
    img: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1332&q=80",
    price: "300",
    discount: "14.67",
    freshness: "Fresh",
    farm: "Farm Pride",
    avgRating: "4",
    stock: "200",
    deliveredTo: "Ibadan",
    estimatedDeliveryDays: "2",
    deliveryMode: "free",
    category: "Bakery",
  },
  {
    id: "3",
    name: "Fresh Fish ",
    description:
      "Fresh Apple with a refreshing taste that helps nourish the body, It contains required body nutrients ranging from vitamins to minerals",
    img: "https://images.unsplash.com/photo-1600699899970-b1c9fadd8f9e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=774&q=80",
    price: "30",
    discount: "14.67",
    freshness: "Fresh",
    farm: "Farm Pride",
    avgRating: "4",
    stock: "200",
    deliveredTo: "Ilorin",
    estimatedDeliveryDays: "1",
    deliveryMode: "free",
    category: "meat and fish",
  },
  {
    id: "4",
    name: "Fresh Meat ",
    description:
      "Fresh Apple with a refreshing taste that helps nourish the body, It contains required body nutrients ranging from vitamins to minerals",
    img: "https://images.unsplash.com/photo-1592686092916-672fa9e86866?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    price: "30",
    discount: "14.67",
    freshness: "Fresh",
    farm: "Farm Pride",
    avgRating: "4",
    stock: "200",
    deliveredTo: "Ilorin",
    estimatedDeliveryDays: "1",
    deliveryMode: "free",
    category: "meat and fish",
  },
  {
    id: "5",
    name: "Spoons ",
    description:
      "Fresh spoons with a refreshing taste that helps nourish the body, It contains required body nutrients ranging from vitamins to minerals",
    img: "https://images.unsplash.com/photo-1525182461131-614d0df14944?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80",
    price: "30",
    discount: "14.67",
    freshness: "Fresh",
    farm: "Farm Pride",
    avgRating: "4",
    stock: "200",
    deliveredTo: "Ilorin",
    estimatedDeliveryDays: "1",
    deliveryMode: "free",
    category: "Kitchen",
  },
  {
    id: "6",
    name: "Golden Morn ",
    description:
      "Golden Morn with a refreshing taste that helps nourish the body, It contains required body nutrients ranging from vitamins to minerals",
    img: "https://images.unsplash.com/photo-1521483451569-e33803c0330c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1085&q=80",
    price: "30",
    discount: "14.67",
    freshness: "Fresh",
    farm: "Farm Pride",
    avgRating: "4",
    stock: "200",
    deliveredTo: "Ilorin",
    estimatedDeliveryDays: "1",
    deliveryMode: "free",
    category: "Pharmacy",
  },
  {
    id: "7",
    name: "Fresh Wine ",
    description:
      "Fresh Apple, Pomegante wine with a refreshing taste that helps nourish the body, It contains required body nutrients ranging from vitamins to minerals",
    img: "https://images.unsplash.com/photo-1603569283847-aa295f0d016a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=772&q=80",
    price: "30",
    discount: "14.67",
    freshness: "Fresh",
    farm: "Farm Pride",
    avgRating: "4",
    stock: "200",
    deliveredTo: "Ilorin",
    estimatedDeliveryDays: "1",
    deliveryMode: "free",
    category: "Drinks",
  },
  {
    id: "8",
    name: "Baby Diapers ",
    description: "Baby diapers for comfort",
    img: "https://images.unsplash.com/photo-1584839404042-8bc21d240e91?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    price: "30",
    discount: "14.67",
    freshness: "Fresh",
    farm: "Farm Pride",
    avgRating: "4",
    stock: "200",
    deliveredTo: "Ilorin",
    estimatedDeliveryDays: "1",
    deliveryMode: "free",
    category: "Pharmacy",
  },
  {
    id: "9",
    name: "Fresh Pineapple ",
    description:
      "Fresh pineapple with a refreshing taste that helps nourish the body, It contains required body nutrients ranging from vitamins to minerals",
    img: "https://images.unsplash.com/photo-1587883012610-e3df17d41270?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80",
    price: "30",
    discount: "14.67",
    freshness: "Fresh",
    farm: "Farm Pride",
    avgRating: "4",
    stock: "200",
    deliveredTo: "Ilorin",
    estimatedDeliveryDays: "1",
    deliveryMode: "free",
    category: "fruits and vegetables",
  },
  {
    id: "10",
    name: "Fresh Pomegranate ",
    description:
      "Fresh pomegranate with a refreshing taste that helps nourish the body, It contains required body nutrients ranging from vitamins to minerals",
    img: "https://images.unsplash.com/photo-1541344999736-83eca272f6fc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    price: "30",
    discount: "14.67",
    freshness: "Fresh",
    farm: "Farm Pride",
    avgRating: "4",
    stock: "200",
    deliveredTo: "Ilorin",
    estimatedDeliveryDays: "1",
    deliveryMode: "free",
    category: "fruits and vegetables",
  },
  {
    id: "11",
    name: "Veggiee Combo ",
    description:
      "Fresh veggie combo with a refreshing taste that helps nourish the body, It contains required body nutrients ranging from vitamins to minerals",
    img: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1153&q=80",
    price: "30",
    discount: "14.67",
    freshness: "Fresh",
    farm: "Farm Pride",
    avgRating: "4",
    stock: "200",
    deliveredTo: "Ilorin",
    estimatedDeliveryDays: "1",
    deliveryMode: "free",
    category: "special nutrition",
  },
];

export default products;
